apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dep
  labels:
    tier: frontend
spec:
  selector: 
    matchLabels:
      app: my-app    
  replicas: 6
  template:
    metadata:
      name: nginx-x
      labels:
        app: my-app 
    spec:
      containers:
        - name: nginx
          image: nginx