apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    name: result-service
    app: test-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010
  selector:
    name: result-pod
    app: test-voting-app