apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-dep
  labels:
    name: result-dep
    app: test-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-pod
      app: test-voting-app
  template:
    metadata:
      name: result-pod
      labels:
        name: result-pod
        app: test-voting-app
    spec:
      containers:
        - name: result
          image: kodekloud/examplevotingapp_result:v1   
          ports:
            - containerPort: 80