apiVersion: apps/v1
kind: Deployment
metadata:
  name: voiting-dep
  labels:
    name: voiting-dep
    app: test-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-pod
      app: test-voting-app
  template:
    metadata:
      name: voting-pod
      labels:
        name: voting-pod
        app: test-voting-app
    spec:
      containers:
        - name: voting
          image: kodekloud/examplevotingapp_vote:v1   
          ports:
            - containerPort: 80
            