apiVersion: v1
kind: Service
metadata:
  name: voting
  labels:
    name: voting-service
    app: test-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30011
  selector:
    name: voting-pod
    app: test-voting-app