apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    name: voting-pod
    app: test-voting-app
spec:
  containers:
    - name: voting
      image: kodekloud/examplevotingapp_vote:v1   
      ports:
        - containerPort: 80
        
